In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
from pathlib import Path

BASE_DIR = Path("/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE")
DATA_DIR = BASE_DIR / "data"
SRC_DIR = BASE_DIR / "src"
OUT_DIR = BASE_DIR / "outputs"

OUT_DIR.mkdir(parents=True, exist_ok=True)

print(DATA_DIR)
print(list(DATA_DIR.iterdir()))

/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data
[PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/X_val.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/X_train.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/dates_train.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/dates_test.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/X_test.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/dates_val.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/scaler_info.json'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/panel_features.parquet'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/X_test_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/obs_train_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/X_train_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/dates_val_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/dates_test_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/X_val_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/dates_train_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/obs_val_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/obs_test_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/miss_train_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/miss_val_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/miss_test_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/panel_features (1).parquet'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/mixture_vae_3state_grid_results.csv'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/mixture_vae_3state_final_test_states.parquet'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/mixture_vae_3state_final_regime_summary.csv'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/mixture_vae_3state_final_feature_summary.csv'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/X_train_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/miss_val_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/obs_val_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/dates_test_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/dates_val_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/X_test_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/miss_test_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/dates_train_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/miss_train_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/X_val_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/obs_train_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/obs_test_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/scaler_info_3.json'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/panel_features_3.parquet'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/X_train_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/X_val_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/obs_train_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/dates_val_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/dates_test_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/obs_val_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/miss_test_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/X_test_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/miss_val_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/dates_train_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/miss_train_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/obs_test_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/scaler_info_4.json'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/panel_features_4.parquet'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του X_val_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του X_test.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του X_train_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του X_val (1).npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του X_val_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του X_test_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του X_train_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του X_train.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του X_train_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του X_val_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του panel_features.parquet'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του panel_features_3.parquet'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του obs_val_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του scaler_info_3.json'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του panel_features_4.parquet'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του X_test_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του X_test_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του scaler_info_4.json'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του panel_features (1).parquet'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του scaler_info.json'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του obs_test_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του obs_val_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του obs_train_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του obs_val_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του obs_test_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του mixture_vae_3state_grid_results.csv'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του obs_train_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του obs_train_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του obs_test_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του mixture_vae_3state_final_test_states.parquet'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του miss_train_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του mixture_vae_3state_final_feature_summary.csv'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του miss_train_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του miss_test_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του miss_val_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του mixture_vae_3state_final_regime_summary.csv'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του miss_train_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του miss_test_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του miss_val_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του miss_val_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του dates_val.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του dates_train_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του dates_test.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του dates_train.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του dates_train_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του dates_val_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του dates_val_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του miss_test_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του dates_train_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του dates_val_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του dates_test_2.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του dates_test_3.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του dates_test_4.npy'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/data/Αντίγραφο του X_val.npy')]

In [3]:
import numpy as np

X_train = np.load(DATA_DIR / "X_train_4.npy")
X_val = np.load(DATA_DIR / "X_val_4.npy")
X_test = np.load(DATA_DIR / "X_test_4.npy")

print(X_train.shape, X_val.shape, X_test.shape)

(5522, 391, 19) (1258, 391, 19) (1453, 391, 19)

In [4]:
import sys
sys.path.append(str(SRC_DIR))

from vae_module import VAEModule

In [5]:
print("SRC_DIR:", SRC_DIR)
print("Files in src:", list(SRC_DIR.iterdir()))

SRC_DIR: /content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/src
Files in src: [PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/src/mixture_vae.py'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/src/vae_module.py'), PosixPath('/content/drive/MyDrive/Aueb_Thesis/Empirical_Study/Mixture_VAE/src/__pycache__')]

In [6]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("No GPU detected. Go to Runtime > Change runtime type > GPU.")

PyTorch: 2.11.0+cu128
CUDA available: True
GPU: NVIDIA A100-SXM4-80GB

In [9]:
from torch.utils.data import TensorDataset, DataLoader
import torch

batch_size = 256
pin = torch.cuda.is_available()

train_ds = TensorDataset(torch.tensor(X_train, dtype=torch.float32))
val_ds = TensorDataset(torch.tensor(X_val, dtype=torch.float32))
test_ds = TensorDataset(torch.tensor(X_test, dtype=torch.float32))

train_loader = DataLoader(
    train_ds,
    batch_size=batch_size,
    shuffle=True,
    drop_last=False,
    num_workers=0,
    pin_memory=pin,
)

val_loader = DataLoader(
    val_ds,
    batch_size=batch_size,
    shuffle=False,
    drop_last=False,
    num_workers=0,
    pin_memory=pin,
)

test_loader = DataLoader(
    test_ds,
    batch_size=batch_size,
    shuffle=False,
    drop_last=False,
    num_workers=0,
    pin_memory=pin,
)

In [48]:
from types import SimpleNamespace

args = SimpleNamespace(
    name="mixture_vae",

    feature=X_train.shape[-1],
    seq_len=X_train.shape[1],
    n_cluster=2,
    hidden_dim=16,

    tau=0.5,
    hard=False,

    reconstruction_on_s=True,
    reconstruction_on_z="p",

    lamda_m=10.0,
    lamda_i=10.0,
    lamda_t=100.0,
    lamda_b=5.0,

    transition="jump",
    jump_mx=None,

    loss_mode="sum",
    loss_clamp=batch_size * X_train.shape[1] * 10,

    s_clamp=5.0,
    eps=1e-8,
    logvar_min=-10.0,
    logvar_max=10.0,

    s_x_type="lstm",
    s_x_lstm_hidden=64,
    s_x_lstm_layers=1,
    s_x_dropout=0.1,

    z_sx_type="mlp",
    z_sx_hiddens=[128, 128],
    z_sx_dropout=0.1,

    x_sz_type="mlp",
    x_sz_hiddens=[128, 128],
    x_sz_dropout=0.1,

    x_z_type="mlp",
    x_z_hiddens=[128, 128],
    x_z_dropout=0.1,
)

print("Feature dim:", args.feature)
print("Sequence length:", args.seq_len)
print("Batch size:", batch_size)
print("Loss clamp:", args.loss_clamp)

Feature dim: 19
Sequence length: 391
Batch size: 256
Loss clamp: 1000960

In [7]:
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True
torch.backends.cudnn.benchmark = True

In [11]:
import itertools

search_space = {
    "lamda_m": [10.0],
    "lamda_i": [10.0],
    "lamda_t": [10.0, 20.0, 30.0, 50.0, 75.0, 100.0],
    "lamda_b": [1.0, 5.0, 10.0],
    "tau": [0.5, 0.7],
}

candidate_configs = [
    {
        "lamda_m": lamda_m,
        "lamda_i": lamda_i,
        "lamda_t": lamda_t,
        "lamda_b": lamda_b,
        "tau": tau,
    }
    for lamda_m, lamda_i, lamda_t, lamda_b, tau in itertools.product(
        search_space["lamda_m"],
        search_space["lamda_i"],
        search_space["lamda_t"],
        search_space["lamda_b"],
        search_space["tau"],
    )
]

print("Number of configs:", len(candidate_configs))
candidate_configs[:5]

Number of configs: 36

[{'lamda_m': 10.0,
  'lamda_i': 10.0,
  'lamda_t': 10.0,
  'lamda_b': 1.0,
  'tau': 0.5},
 {'lamda_m': 10.0,
  'lamda_i': 10.0,
  'lamda_t': 10.0,
  'lamda_b': 1.0,
  'tau': 0.7},
 {'lamda_m': 10.0,
  'lamda_i': 10.0,
  'lamda_t': 10.0,
  'lamda_b': 5.0,
  'tau': 0.5},
 {'lamda_m': 10.0,
  'lamda_i': 10.0,
  'lamda_t': 10.0,
  'lamda_b': 5.0,
  'tau': 0.7},
 {'lamda_m': 10.0,
  'lamda_i': 10.0,
  'lamda_t': 10.0,
  'lamda_b': 10.0,
  'tau': 0.5}]

In [12]:
import copy
import numpy as np
import pandas as pd
import time
import torch

results = []
candidate_models = {}
candidate_histories = {}

for i, cfg in enumerate(candidate_configs, start=1):
    args_run = copy.deepcopy(args)

    args_run.lamda_m = cfg["lamda_m"]
    args_run.lamda_i = cfg["lamda_i"]
    args_run.lamda_t = cfg["lamda_t"]
    args_run.lamda_b = cfg["lamda_b"]
    args_run.tau = cfg["tau"]

    key = (
        cfg["lamda_m"],
        cfg["lamda_i"],
        cfg["lamda_t"],
        cfg["tau"],
        cfg["lamda_b"],
    )

    print("=" * 100)
    print(f"Config {i}/{len(candidate_configs)}")
    print(
        f"Running Mixture-VAE | "
        f"lamda_m={cfg['lamda_m']}, "
        f"lamda_i={cfg['lamda_i']}, "
        f"lamda_t={cfg['lamda_t']}, "
        f"tau={cfg['tau']}, "
        f"lamda_b={cfg['lamda_b']}"
    )

    start_time = time.time()

    vae_run = VAEModule(args_run)

    history_run = vae_run.fit(
        train_loader=train_loader,
        val_loader=val_loader,
        lr=1e-3,
        epochs=40,
        weight_decay=1e-5,
        patience=15,
        verbose=True,
    )

    elapsed_sec = time.time() - start_time

    if len(history_run["val_loss"]) == 0:
        print("No validation loss recorded. Skipping.")
        continue

    best_epoch_idx = int(np.argmin(history_run["val_loss"]))

    best_usage = np.asarray(history_run["val_regime_usage"][best_epoch_idx])
    best_eff = float(history_run["val_effective_regimes"][best_epoch_idx])
    best_switch = float(history_run["val_switch_rate"][best_epoch_idx])

    result = {
        "lamda_m": cfg["lamda_m"],
        "lamda_i": cfg["lamda_i"],
        "lamda_t": cfg["lamda_t"],
        "tau": cfg["tau"],
        "lamda_b": cfg["lamda_b"],

        "best_epoch": best_epoch_idx + 1,
        "elapsed_sec": elapsed_sec,

        "val_total_loss": float(history_run["val_loss"][best_epoch_idx]),
        "val_recon_loss": float(history_run["val_loss_r"][best_epoch_idx]),
        "val_mixture_loss": float(history_run["val_loss_m"][best_epoch_idx]),
        "val_info_loss": float(history_run["val_loss_i"][best_epoch_idx]),
        "val_transition_loss": float(history_run["val_loss_t"][best_epoch_idx]),
        "val_balance_loss": float(history_run["val_loss_b"][best_epoch_idx]),

        "usage_0": float(best_usage[0]),
        "usage_1": float(best_usage[1]),
        "min_usage": float(np.min(best_usage)),
        "max_usage": float(np.max(best_usage)),
        "eff_regimes": best_eff,
        "switch_rate": best_switch,
    }

    result["weighted_mixture"] = result["lamda_m"] * result["val_mixture_loss"]
    result["weighted_info"] = result["lamda_i"] * result["val_info_loss"]
    result["weighted_transition"] = result["lamda_t"] * result["val_transition_loss"]
    result["weighted_balance"] = result["lamda_b"] * result["val_balance_loss"]

    results.append(result)

    candidate_models[key] = vae_run
    candidate_histories[key] = history_run

    results_df = pd.DataFrame(results)
    #results_df.to_csv("mixture_vae_trend_regime_hyperparameter_results.csv", index=False)

    display(
        results_df.sort_values(
            ["min_usage", "switch_rate"],
            ascending=[False, True]
        ).head(10)
    )

====================================================================================================
Config 1/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=10.0, tau=0.5, lamda_b=1.0
Epoch [1/40] | train_loss=25054.612414 | val_total=15828.903418 | val_recon=4141.752484 | usage=[0.2575 0.7425] | eff=1.619 | switch=0.0003
Epoch [10/40] | train_loss=14445.108475 | val_total=12282.734897 | val_recon=3188.724414 | usage=[0.404 0.596] | eff=1.929 | switch=0.0522
Epoch [20/40] | train_loss=14178.421700 | val_total=12081.075517 | val_recon=3026.801023 | usage=[0.428 0.572] | eff=1.959 | switch=0.0532
Epoch [30/40] | train_loss=14108.756157 | val_total=12228.199722 | val_recon=3187.100705 | usage=[0.4484 0.5516] | eff=1.979 | switch=0.0528
Epoch [40/40] | train_loss=14056.542195 | val_total=12081.714825 | val_recon=3045.146810 | usage=[0.4382 0.5618] | eff=1.970 | switch=0.0502

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.05223,9603.704168,-1777.581292,1212.224901,3.248722

====================================================================================================
Config 2/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=10.0, tau=0.7, lamda_b=1.0
Epoch [1/40] | train_loss=23740.577553 | val_total=16133.268680 | val_recon=4117.600755 | usage=[0.5689 0.4311] | eff=1.963 | switch=0.0230
Epoch [10/40] | train_loss=14130.114089 | val_total=12133.138315 | val_recon=3089.997913 | usage=[0.4924 0.5076] | eff=2.000 | switch=0.0615
Epoch [20/40] | train_loss=13912.234245 | val_total=11925.015302 | val_recon=2895.488523 | usage=[0.4788 0.5212] | eff=1.996 | switch=0.0675
Epoch [30/40] | train_loss=13809.267928 | val_total=11855.988076 | val_recon=2843.971333 | usage=[0.4832 0.5168] | eff=1.998 | switch=0.0634
Epoch [40/40] | train_loss=13801.741602 | val_total=12056.400437 | val_recon=3049.442915 | usage=[0.4877 0.5123] | eff=1.999 | switch=0.0560

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.052230,9603.704168,-1777.581292,1212.224901,3.248722

====================================================================================================
Config 3/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=10.0, tau=0.5, lamda_b=5.0
Epoch [1/40] | train_loss=25338.717041 | val_total=16761.998410 | val_recon=4095.237729 | usage=[0.752 0.248] | eff=1.595 | switch=0.0009
Epoch [10/40] | train_loss=14377.119069 | val_total=12259.431638 | val_recon=3183.514805 | usage=[0.5406 0.4594] | eff=1.987 | switch=0.0581
Epoch [20/40] | train_loss=14170.210318 | val_total=12168.267687 | val_recon=3113.650040 | usage=[0.5345 0.4655] | eff=1.991 | switch=0.0588
Epoch [30/40] | train_loss=14060.346432 | val_total=12134.588434 | val_recon=3092.906846 | usage=[0.5294 0.4706] | eff=1.993 | switch=0.0577
Epoch [40/40] | train_loss=14004.267543 | val_total=12091.444157 | val_recon=3059.159678 | usage=[0.5304 0.4696] | eff=1.993 | switch=0.0556

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.052230,9603.704168,-1777.581292,1212.224901,3.248722

====================================================================================================
Config 4/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=10.0, tau=0.7, lamda_b=5.0
Epoch [1/40] | train_loss=27531.296315 | val_total=16968.832870 | val_recon=4139.667478 | usage=[0.3857 0.6143] | eff=1.901 | switch=0.0026
Epoch [10/40] | train_loss=14278.805098 | val_total=12148.196542 | val_recon=3086.466365 | usage=[0.4631 0.5369] | eff=1.989 | switch=0.0618
Epoch [20/40] | train_loss=13985.052381 | val_total=12035.990859 | val_recon=3003.060364 | usage=[0.4701 0.5299] | eff=1.993 | switch=0.0588
Epoch [30/40] | train_loss=13874.293689 | val_total=11905.116653 | val_recon=2884.628080 | usage=[0.4767 0.5233] | eff=1.996 | switch=0.0555
Epoch [40/40] | train_loss=13821.055867 | val_total=11928.818760 | val_recon=2915.589279 | usage=[0.4832 0.5168] | eff=1.998 | switch=0.0553

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.052230,9603.704168,-1777.581292,1212.224901,3.248722

====================================================================================================
Config 5/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=10.0, tau=0.5, lamda_b=10.0
Epoch [1/40] | train_loss=23549.497102 | val_total=16315.631955 | val_recon=4148.272655 | usage=[0.5061 0.4939] | eff=2.000 | switch=0.0399
Epoch [10/40] | train_loss=14359.228201 | val_total=12187.888116 | val_recon=3117.404760 | usage=[0.5246 0.4754] | eff=1.995 | switch=0.0619
Epoch [20/40] | train_loss=14134.074950 | val_total=12115.528219 | val_recon=3074.984499 | usage=[0.5151 0.4849] | eff=1.998 | switch=0.0629
Epoch [30/40] | train_loss=14041.990628 | val_total=12004.059817 | val_recon=2969.040938 | usage=[0.5116 0.4884] | eff=1.999 | switch=0.0610
Epoch [40/40] | train_loss=13981.604627 | val_total=12170.163752 | val_recon=3141.339130 | usage=[0.5182 0.4818] | eff=1.997 | switch=0.0637

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.052230,9603.704168,-1777.581292,1212.224901,3.248722

====================================================================================================
Config 6/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=10.0, tau=0.7, lamda_b=10.0
Epoch [1/40] | train_loss=25619.749909 | val_total=15953.317965 | val_recon=4154.345390 | usage=[0.6621 0.3379] | eff=1.810 | switch=0.0018
Epoch [10/40] | train_loss=14211.536490 | val_total=11978.020469 | val_recon=2929.679551 | usage=[0.512 0.488] | eff=1.999 | switch=0.0693
Epoch [20/40] | train_loss=13977.328414 | val_total=12056.681041 | val_recon=3023.560562 | usage=[0.5115 0.4885] | eff=1.999 | switch=0.0626
Epoch [30/40] | train_loss=13858.836925 | val_total=11935.305843 | val_recon=2912.997417 | usage=[0.5141 0.4859] | eff=1.998 | switch=0.0632
Epoch [40/40] | train_loss=13843.734426 | val_total=12036.037957 | val_recon=3015.672446 | usage=[0.5207 0.4793] | eff=1.997 | switch=0.0582

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.052230,9603.704168,-1777.581292,1212.224901,3.248722

====================================================================================================
Config 7/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=20.0, tau=0.5, lamda_b=1.0
Epoch [1/40] | train_loss=24820.556728 | val_total=16758.135334 | val_recon=4119.702206 | usage=[0.1876 0.8124] | eff=1.438 | switch=0.0013
Epoch [10/40] | train_loss=15142.863274 | val_total=12991.007750 | val_recon=3234.123311 | usage=[0.3877 0.6123] | eff=1.904 | switch=0.0286
Epoch [20/40] | train_loss=14919.577440 | val_total=12784.635533 | val_recon=2986.334261 | usage=[0.4188 0.5812] | eff=1.949 | switch=0.0286
Epoch [30/40] | train_loss=14826.690103 | val_total=12777.052663 | val_recon=2971.458913 | usage=[0.432 0.568] | eff=1.964 | switch=0.0272
Epoch [40/40] | train_loss=14758.870246 | val_total=12927.098967 | val_recon=3118.572039 | usage=[0.4211 0.5789] | eff=1.951 | switch=0.0264

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.052230,9603.704168,-1777.581292,1212.224901,3.248722
6,10.0,10.0,20.0,0.5,1.0,31,15.144653,12706.095390,2901.664199,960.266147,...,0.426174,0.573826,0.426174,0.573826,1.957328,0.027005,9602.661467,-914.766852,1112.219716,4.317261

====================================================================================================
Config 8/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=20.0, tau=0.7, lamda_b=1.0
Epoch [1/40] | train_loss=25938.823117 | val_total=16780.026232 | val_recon=3865.805743 | usage=[0.299 0.701] | eff=1.722 | switch=0.0165
Epoch [10/40] | train_loss=15014.929917 | val_total=12821.500397 | val_recon=3018.692369 | usage=[0.401 0.599] | eff=1.925 | switch=0.0283
Epoch [20/40] | train_loss=14768.816914 | val_total=12651.484499 | val_recon=2832.323927 | usage=[0.4205 0.5795] | eff=1.951 | switch=0.0261
Epoch [30/40] | train_loss=14648.426725 | val_total=12727.172099 | val_recon=2914.983953 | usage=[0.419 0.581] | eff=1.949 | switch=0.0247
Epoch [40/40] | train_loss=14587.481347 | val_total=12787.127782 | val_recon=2979.536367 | usage=[0.42 0.58] | eff=1.950 | switch=0.0241

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.052230,9603.704168,-1777.581292,1212.224901,3.248722
6,10.0,10.0,20.0,0.5,1.0,31,15.144653,12706.095390,2901.664199,960.266147,...,0.426174,0.573826,0.426174,0.573826,1.957328,0.027005,9602.661467,-914.766852,1112.219716,4.317261
7,10.0,10.0,20.0,0.7,1.0,35,15.047179,12612.795509,2809.165143,960.280430,...,0.418863,0.581137,0.418863,0.581137,1.948686,0.024296,9602.804302,-984.845706,1180.431457,5.240554

====================================================================================================
Config 9/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=20.0, tau=0.5, lamda_b=5.0
Epoch [1/40] | train_loss=27555.768064 | val_total=17790.414547 | val_recon=4019.608754 | usage=[0.4222 0.5778] | eff=1.953 | switch=0.0257
Epoch [10/40] | train_loss=15179.060802 | val_total=12913.318760 | val_recon=3147.511427 | usage=[0.484 0.516] | eff=1.998 | switch=0.0308
Epoch [20/40] | train_loss=14962.233068 | val_total=12973.099960 | val_recon=3158.500994 | usage=[0.4694 0.5306] | eff=1.993 | switch=0.0299
Epoch [30/40] | train_loss=14888.021595 | val_total=12733.803259 | val_recon=2906.558277 | usage=[0.4774 0.5226] | eff=1.996 | switch=0.0285
Epoch [40/40] | train_loss=14825.213962 | val_total=12810.516296 | val_recon=2975.705386 | usage=[0.4709 0.5291] | eff=1.993 | switch=0.0277

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.052230,9603.704168,-1777.581292,1212.224901,3.248722
6,10.0,10.0,20.0,0.5,1.0,31,15.144653,12706.095390,2901.664199,960.266147,...,0.426174,0.573826,0.426174,0.573826,1.957328,0.027005,9602.661467,-914.766852,1112.219716,4.317261
7,10.0,10.0,20.0,0.7,1.0,35,15.047179,12612.795509,2809.165143,960.280430,...,0.418863,0.581137,0.418863,0.581137,1.948686,0.024296,9602.804302,-984.845706,1180.431457,5.240554

====================================================================================================
Config 10/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=20.0, tau=0.7, lamda_b=5.0
Epoch [1/40] | train_loss=26706.548307 | val_total=17614.808824 | val_recon=3881.532740 | usage=[0.7775 0.2225] | eff=1.529 | switch=0.0130
Epoch [10/40] | train_loss=14952.596025 | val_total=12899.664746 | val_recon=3027.647655 | usage=[0.6172 0.3828] | eff=1.896 | switch=0.0287
Epoch [20/40] | train_loss=14717.442706 | val_total=12704.406598 | val_recon=2852.490461 | usage=[0.5969 0.4031] | eff=1.928 | switch=0.0249
Epoch [30/40] | train_loss=14579.051272 | val_total=12646.129571 | val_recon=2819.072685 | usage=[0.5955 0.4045] | eff=1.930 | switch=0.0235
Epoch [40/40] | train_loss=14545.282778 | val_total=12637.032989 | val_recon=2822.331230 | usage=[0.5918 0.4082] | eff=1.935 | switch=0.0236

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.052230,9603.704168,-1777.581292,1212.224901,3.248722
6,10.0,10.0,20.0,0.5,1.0,31,15.144653,12706.095390,2901.664199,960.266147,...,0.426174,0.573826,0.426174,0.573826,1.957328,0.027005,9602.661467,-914.766852,1112.219716,4.317261
7,10.0,10.0,20.0,0.7,1.0,35,15.047179,12612.795509,2809.165143,960.280430,...,0.418863,0.581137,0.418863,0.581137,1.948686,0.024296,9602.804302,-984.845706,1180.431457,5.240554
9,10.0,10.0,20.0,0.7,5.0,38,15.199067,12578.501789,2752.145394,960.311568,...,0.582463,0.417537,0.417537,0.582463,1.947040,0.024237,9603.115685,-997.147832,1190.224004,30.164121

====================================================================================================
Config 11/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=20.0, tau=0.5, lamda_b=10.0
Epoch [1/40] | train_loss=29421.639986 | val_total=18914.314388 | val_recon=3953.433873 | usage=[0.443 0.557] | eff=1.974 | switch=0.0261
Epoch [10/40] | train_loss=15208.828368 | val_total=12936.302464 | val_recon=3120.377534 | usage=[0.4331 0.5669] | eff=1.965 | switch=0.0307
Epoch [20/40] | train_loss=14980.583756 | val_total=12928.156002 | val_recon=3081.994088 | usage=[0.4356 0.5644] | eff=1.967 | switch=0.0291
Epoch [30/40] | train_loss=14883.755388 | val_total=12798.829491 | val_recon=2944.541733 | usage=[0.4426 0.5574] | eff=1.974 | switch=0.0283
Epoch [40/40] | train_loss=14817.880252 | val_total=12782.045707 | val_recon=2931.789000 | usage=[0.4532 0.5468] | eff=1.983 | switch=0.0276

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
10,10.0,10.0,20.0,0.5,10.0,33,15.042145,12705.368243,2854.356816,960.601923,...,0.450298,0.549702,0.450298,0.549702,1.980431,0.028474,9606.019227,-968.155042,1189.869849,23.277189
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.052230,9603.704168,-1777.581292,1212.224901,3.248722
6,10.0,10.0,20.0,0.5,1.0,31,15.144653,12706.095390,2901.664199,960.266147,...,0.426174,0.573826,0.426174,0.573826,1.957328,0.027005,9602.661467,-914.766852,1112.219716,4.317261
7,10.0,10.0,20.0,0.7,1.0,35,15.047179,12612.795509,2809.165143,960.280430,...,0.418863,0.581137,0.418863,0.581137,1.948686,0.024296,9602.804302,-984.845706,1180.431457,5.240554

====================================================================================================
Config 12/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=20.0, tau=0.7, lamda_b=10.0
Epoch [1/40] | train_loss=26720.485694 | val_total=16606.875795 | val_recon=3646.191226 | usage=[0.7029 0.2971] | eff=1.717 | switch=0.0236
Epoch [10/40] | train_loss=14999.115809 | val_total=12872.815580 | val_recon=2981.118740 | usage=[0.5781 0.4219] | eff=1.952 | switch=0.0312
Epoch [20/40] | train_loss=14746.578866 | val_total=12795.358704 | val_recon=2928.447089 | usage=[0.5698 0.4302] | eff=1.962 | switch=0.0265
Epoch [30/40] | train_loss=14625.998189 | val_total=12637.769078 | val_recon=2803.587391 | usage=[0.5585 0.4415] | eff=1.973 | switch=0.0248
Epoch [40/40] | train_loss=14564.154066 | val_total=12642.325318 | val_recon=2818.866256 | usage=[0.5559 0.4441] | eff=1.975 | switch=0.0248

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
10,10.0,10.0,20.0,0.5,10.0,33,15.042145,12705.368243,2854.356816,960.601923,...,0.450298,0.549702,0.450298,0.549702,1.980431,0.028474,9606.019227,-968.155042,1189.869849,23.277189
11,10.0,10.0,20.0,0.7,10.0,38,15.195187,12581.158983,2758.670906,960.255564,...,0.554936,0.445064,0.445064,0.554936,1.976144,0.024502,9602.555644,-976.492060,1167.940012,28.484556
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.052230,9603.704168,-1777.581292,1212.224901,3.248722
6,10.0,10.0,20.0,0.5,1.0,31,15.144653,12706.095390,2901.664199,960.266147,...,0.426174,0.573826,0.426174,0.573826,1.957328,0.027005,9602.661467,-914.766852,1112.219716,4.317261

====================================================================================================
Config 13/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=30.0, tau=0.5, lamda_b=1.0
Epoch [1/40] | train_loss=31734.489270 | val_total=19859.844595 | val_recon=4017.409380 | usage=[0.6895 0.3105] | eff=1.749 | switch=0.0202
Epoch [10/40] | train_loss=15491.907959 | val_total=13165.726749 | val_recon=3331.485046 | usage=[0.624 0.376] | eff=1.884 | switch=0.0194
Epoch [20/40] | train_loss=15338.232977 | val_total=13102.932035 | val_recon=3280.474314 | usage=[0.587 0.413] | eff=1.941 | switch=0.0205
Epoch [30/40] | train_loss=15255.007470 | val_total=13074.556041 | val_recon=3257.945002 | usage=[0.5728 0.4272] | eff=1.959 | switch=0.0185
Epoch [40/40] | train_loss=15215.357026 | val_total=13177.306240 | val_recon=3319.730326 | usage=[0.6127 0.3873] | eff=1.903 | switch=0.0183

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
10,10.0,10.0,20.0,0.5,10.0,33,15.042145,12705.368243,2854.356816,960.601923,...,0.450298,0.549702,0.450298,0.549702,1.980431,0.028474,9606.019227,-968.155042,1189.869849,23.277189
11,10.0,10.0,20.0,0.7,10.0,38,15.195187,12581.158983,2758.670906,960.255564,...,0.554936,0.445064,0.445064,0.554936,1.976144,0.024502,9602.555644,-976.492060,1167.940012,28.484556
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.052230,9603.704168,-1777.581292,1212.224901,3.248722
6,10.0,10.0,20.0,0.5,1.0,31,15.144653,12706.095390,2901.664199,960.266147,...,0.426174,0.573826,0.426174,0.573826,1.957328,0.027005,9602.661467,-914.766852,1112.219716,4.317261

====================================================================================================
Config 14/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=30.0, tau=0.7, lamda_b=1.0
Epoch [1/40] | train_loss=29679.437432 | val_total=19351.350954 | val_recon=3958.011824 | usage=[0.7429 0.2571] | eff=1.618 | switch=0.0160
Epoch [10/40] | train_loss=15468.590230 | val_total=13114.304452 | val_recon=3254.694157 | usage=[0.6693 0.3307] | eff=1.794 | switch=0.0176
Epoch [20/40] | train_loss=15166.502490 | val_total=13085.729531 | val_recon=3176.556339 | usage=[0.658 0.342] | eff=1.818 | switch=0.0172
Epoch [30/40] | train_loss=14998.892838 | val_total=12940.171105 | val_recon=2998.646463 | usage=[0.6463 0.3537] | eff=1.842 | switch=0.0177
Epoch [40/40] | train_loss=14923.178558 | val_total=12879.904213 | val_recon=2952.092160 | usage=[0.6964 0.3036] | eff=1.733 | switch=0.0146

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
10,10.0,10.0,20.0,0.5,10.0,33,15.042145,12705.368243,2854.356816,960.601923,...,0.450298,0.549702,0.450298,0.549702,1.980431,0.028474,9606.019227,-968.155042,1189.869849,23.277189
11,10.0,10.0,20.0,0.7,10.0,38,15.195187,12581.158983,2758.670906,960.255564,...,0.554936,0.445064,0.445064,0.554936,1.976144,0.024502,9602.555644,-976.492060,1167.940012,28.484556
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.052230,9603.704168,-1777.581292,1212.224901,3.248722
6,10.0,10.0,20.0,0.5,1.0,31,15.144653,12706.095390,2901.664199,960.266147,...,0.426174,0.573826,0.426174,0.573826,1.957328,0.027005,9602.661467,-914.766852,1112.219716,4.317261

====================================================================================================
Config 15/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=30.0, tau=0.5, lamda_b=5.0
Epoch [1/40] | train_loss=29426.413301 | val_total=19329.577107 | val_recon=4017.804054 | usage=[0.8205 0.1795] | eff=1.418 | switch=0.0040
Epoch [10/40] | train_loss=15441.971116 | val_total=13101.183426 | val_recon=3266.950417 | usage=[0.542 0.458] | eff=1.986 | switch=0.0208
Epoch [20/40] | train_loss=15290.323705 | val_total=13055.460851 | val_recon=3230.865958 | usage=[0.5275 0.4725] | eff=1.994 | switch=0.0202
Epoch [30/40] | train_loss=15211.141796 | val_total=13234.248211 | val_recon=3359.112331 | usage=[0.5282 0.4718] | eff=1.994 | switch=0.0215
Epoch [40/40] | train_loss=15152.611961 | val_total=13073.766892 | val_recon=3161.378478 | usage=[0.5152 0.4848] | eff=1.998 | switch=0.0219

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
10,10.0,10.0,20.0,0.5,10.0,33,15.042145,12705.368243,2854.356816,960.601923,...,0.450298,0.549702,0.450298,0.549702,1.980431,0.028474,9606.019227,-968.155042,1189.869849,23.277189
11,10.0,10.0,20.0,0.7,10.0,38,15.195187,12581.158983,2758.670906,960.255564,...,0.554936,0.445064,0.445064,0.554936,1.976144,0.024502,9602.555644,-976.492060,1167.940012,28.484556
0,10.0,10.0,10.0,0.5,1.0,29,21.957585,12000.746025,2959.149444,960.370417,...,0.437714,0.562286,0.437714,0.562286,1.969438,0.052230,9603.704168,-1777.581292,1212.224901,3.248722

====================================================================================================
Config 16/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=30.0, tau=0.7, lamda_b=5.0
Epoch [1/40] | train_loss=29334.558086 | val_total=18167.948927 | val_recon=3763.768134 | usage=[0.7394 0.2606] | eff=1.627 | switch=0.0179
Epoch [10/40] | train_loss=15422.204274 | val_total=13070.959658 | val_recon=3203.629223 | usage=[0.5338 0.4662] | eff=1.991 | switch=0.0204
Epoch [20/40] | train_loss=15157.791787 | val_total=12944.053458 | val_recon=3036.891494 | usage=[0.5472 0.4528] | eff=1.982 | switch=0.0175
Epoch [30/40] | train_loss=15012.898723 | val_total=12881.612083 | val_recon=2944.042130 | usage=[0.5362 0.4638] | eff=1.990 | switch=0.0173
Epoch [40/40] | train_loss=14925.789592 | val_total=12951.052067 | val_recon=3013.360244 | usage=[0.5448 0.4552] | eff=1.984 | switch=0.0166

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
15,10.0,10.0,30.0,0.7,5.0,36,15.440932,12858.564587,2916.268879,960.364095,...,0.548612,0.451388,0.451388,0.548612,1.981272,0.017137,9603.640948,-499.574062,828.877341,9.351308
10,10.0,10.0,20.0,0.5,10.0,33,15.042145,12705.368243,2854.356816,960.601923,...,0.450298,0.549702,0.450298,0.549702,1.980431,0.028474,9606.019227,-968.155042,1189.869849,23.277189
11,10.0,10.0,20.0,0.7,10.0,38,15.195187,12581.158983,2758.670906,960.255564,...,0.554936,0.445064,0.445064,0.554936,1.976144,0.024502,9602.555644,-976.492060,1167.940012,28.484556

====================================================================================================
Config 17/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=30.0, tau=0.5, lamda_b=10.0
Epoch [1/40] | train_loss=30323.147999 | val_total=20505.810413 | val_recon=3969.731568 | usage=[0.5987 0.4013] | eff=1.925 | switch=0.0339
Epoch [10/40] | train_loss=15477.350869 | val_total=13131.050278 | val_recon=3266.758396 | usage=[0.479 0.521] | eff=1.996 | switch=0.0230
Epoch [20/40] | train_loss=15324.713691 | val_total=13030.255763 | val_recon=3191.382055 | usage=[0.493 0.507] | eff=2.000 | switch=0.0202
Epoch [30/40] | train_loss=15231.504505 | val_total=13063.759141 | val_recon=3163.385831 | usage=[0.4773 0.5227] | eff=1.996 | switch=0.0206
Epoch [40/40] | train_loss=15158.484879 | val_total=12966.439587 | val_recon=3055.410374 | usage=[0.4867 0.5133] | eff=1.999 | switch=0.0204

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
15,10.0,10.0,30.0,0.7,5.0,36,15.440932,12858.564587,2916.268879,960.364095,...,0.548612,0.451388,0.451388,0.548612,1.981272,0.017137,9603.640948,-499.574062,828.877341,9.351308
10,10.0,10.0,20.0,0.5,10.0,33,15.042145,12705.368243,2854.356816,960.601923,...,0.450298,0.549702,0.450298,0.549702,1.980431,0.028474,9606.019227,-968.155042,1189.869849,23.277189

====================================================================================================
Config 18/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=30.0, tau=0.7, lamda_b=10.0
Epoch [1/40] | train_loss=30912.343082 | val_total=19724.059221 | val_recon=3756.822089 | usage=[0.794 0.206] | eff=1.486 | switch=0.0104
Epoch [10/40] | train_loss=15441.478314 | val_total=13134.644873 | val_recon=3189.177663 | usage=[0.5933 0.4067] | eff=1.933 | switch=0.0209
Epoch [20/40] | train_loss=15190.770690 | val_total=13131.929849 | val_recon=3150.630614 | usage=[0.5921 0.4079] | eff=1.934 | switch=0.0195
Epoch [30/40] | train_loss=15073.763808 | val_total=12926.256558 | val_recon=2951.095191 | usage=[0.5656 0.4344] | eff=1.966 | switch=0.0174
Epoch [40/40] | train_loss=14937.110965 | val_total=13009.256558 | val_recon=3013.062699 | usage=[0.568 0.432] | eff=1.964 | switch=0.0172

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
15,10.0,10.0,30.0,0.7,5.0,36,15.440932,12858.564587,2916.268879,960.364095,...,0.548612,0.451388,0.451388,0.548612,1.981272,0.017137,9603.640948,-499.574062,828.877341,9.351308
10,10.0,10.0,20.0,0.5,10.0,33,15.042145,12705.368243,2854.356816,960.601923,...,0.450298,0.549702,0.450298,0.549702,1.980431,0.028474,9606.019227,-968.155042,1189.869849,23.277189

====================================================================================================
Config 19/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=50.0, tau=0.5, lamda_b=1.0
Epoch [1/40] | train_loss=29926.574928 | val_total=20356.943164 | val_recon=3612.140004 | usage=[0.5978 0.4022] | eff=1.926 | switch=0.0197
Epoch [10/40] | train_loss=15572.605668 | val_total=13297.304849 | val_recon=3416.400537 | usage=[0.7604 0.2396] | eff=1.573 | switch=0.0091
Epoch [20/40] | train_loss=15423.701105 | val_total=13240.204293 | val_recon=3362.651679 | usage=[0.7959 0.2041] | eff=1.481 | switch=0.0092
Epoch [30/40] | train_loss=15402.776847 | val_total=13414.227345 | val_recon=3523.392836 | usage=[0.8928 0.1072] | eff=1.237 | switch=0.0040
Early stopping at epoch 35. Best val loss = 13240.204293

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
15,10.0,10.0,30.0,0.7,5.0,36,15.440932,12858.564587,2916.268879,960.364095,...,0.548612,0.451388,0.451388,0.548612,1.981272,0.017137,9603.640948,-499.574062,828.877341,9.351308
10,10.0,10.0,20.0,0.5,10.0,33,15.042145,12705.368243,2854.356816,960.601923,...,0.450298,0.549702,0.450298,0.549702,1.980431,0.028474,9606.019227,-968.155042,1189.869849,23.277189

====================================================================================================
Config 20/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=50.0, tau=0.7, lamda_b=1.0
Epoch [1/40] | train_loss=31444.807543 | val_total=19796.250795 | val_recon=4037.447387 | usage=[0.1781 0.8219] | eff=1.414 | switch=0.0002
Epoch [10/40] | train_loss=15764.824203 | val_total=13461.980525 | val_recon=3516.636178 | usage=[0.184 0.816] | eff=1.429 | switch=0.0076
Epoch [20/40] | train_loss=15524.153386 | val_total=13279.449126 | val_recon=3385.585702 | usage=[0.3711 0.6289] | eff=1.875 | switch=0.0129
Epoch [30/40] | train_loss=15437.492304 | val_total=13251.010533 | val_recon=3248.819754 | usage=[0.4153 0.5847] | eff=1.944 | switch=0.0144
Epoch [40/40] | train_loss=15367.075969 | val_total=13194.194555 | val_recon=3179.736437 | usage=[0.2809 0.7191] | eff=1.678 | switch=0.0134

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
15,10.0,10.0,30.0,0.7,5.0,36,15.440932,12858.564587,2916.268879,960.364095,...,0.548612,0.451388,0.451388,0.548612,1.981272,0.017137,9603.640948,-499.574062,828.877341,9.351308
10,10.0,10.0,20.0,0.5,10.0,33,15.042145,12705.368243,2854.356816,960.601923,...,0.450298,0.549702,0.450298,0.549702,1.980431,0.028474,9606.019227,-968.155042,1189.869849,23.277189

====================================================================================================
Config 21/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=50.0, tau=0.5, lamda_b=5.0
Epoch [1/40] | train_loss=34104.954002 | val_total=21114.903021 | val_recon=3765.816673 | usage=[0.7615 0.2385] | eff=1.570 | switch=0.0134
Epoch [10/40] | train_loss=15697.484698 | val_total=13443.350159 | val_recon=3365.777723 | usage=[0.722 0.278] | eff=1.671 | switch=0.0108
Epoch [20/40] | train_loss=15532.651847 | val_total=13284.296105 | val_recon=3380.876143 | usage=[0.629 0.371] | eff=1.875 | switch=0.0115
Epoch [30/40] | train_loss=15457.667557 | val_total=13297.629571 | val_recon=3326.066176 | usage=[0.6551 0.3449] | eff=1.824 | switch=0.0140
Epoch [40/40] | train_loss=15427.072256 | val_total=13298.965620 | val_recon=3324.824523 | usage=[0.6584 0.3416] | eff=1.818 | switch=0.0139

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
15,10.0,10.0,30.0,0.7,5.0,36,15.440932,12858.564587,2916.268879,960.364095,...,0.548612,0.451388,0.451388,0.548612,1.981272,0.017137,9603.640948,-499.574062,828.877341,9.351308
10,10.0,10.0,20.0,0.5,10.0,33,15.042145,12705.368243,2854.356816,960.601923,...,0.450298,0.549702,0.450298,0.549702,1.980431,0.028474,9606.019227,-968.155042,1189.869849,23.277189

====================================================================================================
Config 22/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=50.0, tau=0.7, lamda_b=5.0
Epoch [1/40] | train_loss=32191.771143 | val_total=20244.746423 | val_recon=3676.404312 | usage=[0.7112 0.2888] | eff=1.697 | switch=0.0192
Epoch [10/40] | train_loss=15642.894377 | val_total=13367.125199 | val_recon=3360.732214 | usage=[0.6781 0.3219] | eff=1.775 | switch=0.0113
Epoch [20/40] | train_loss=15487.910947 | val_total=13353.783983 | val_recon=3336.965819 | usage=[0.6867 0.3133] | eff=1.755 | switch=0.0128
Epoch [30/40] | train_loss=15428.919504 | val_total=13297.728537 | val_recon=3317.993293 | usage=[0.6741 0.3259] | eff=1.784 | switch=0.0121
Epoch [40/40] | train_loss=15389.750498 | val_total=13281.773052 | val_recon=3261.946194 | usage=[0.6856 0.3144] | eff=1.758 | switch=0.0130

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
15,10.0,10.0,30.0,0.7,5.0,36,15.440932,12858.564587,2916.268879,960.364095,...,0.548612,0.451388,0.451388,0.548612,1.981272,0.017137,9603.640948,-499.574062,828.877341,9.351308
10,10.0,10.0,20.0,0.5,10.0,33,15.042145,12705.368243,2854.356816,960.601923,...,0.450298,0.549702,0.450298,0.549702,1.980431,0.028474,9606.019227,-968.155042,1189.869849,23.277189

====================================================================================================
Config 23/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=50.0, tau=0.5, lamda_b=10.0
Epoch [1/40] | train_loss=31049.532687 | val_total=20510.567568 | val_recon=4031.192667 | usage=[0.8951 0.1049] | eff=1.231 | switch=0.0012
Epoch [10/40] | train_loss=15701.887677 | val_total=13419.162361 | val_recon=3564.484400 | usage=[0.5961 0.4039] | eff=1.929 | switch=0.0084
Epoch [20/40] | train_loss=15544.109064 | val_total=13261.823331 | val_recon=3392.509191 | usage=[0.5258 0.4742] | eff=1.995 | switch=0.0136
Epoch [30/40] | train_loss=15485.209978 | val_total=13294.282194 | val_recon=3395.896761 | usage=[0.5458 0.4542] | eff=1.983 | switch=0.0143
Early stopping at epoch 38. Best val loss = 13261.227941

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
22,10.0,10.0,50.0,0.5,10.0,23,14.424851,13261.227941,3404.360791,960.351413,...,0.522383,0.477617,0.477617,0.522383,1.996000,0.013330,9603.514135,-66.758273,315.849244,4.262317
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936
15,10.0,10.0,30.0,0.7,5.0,36,15.440932,12858.564587,2916.268879,960.364095,...,0.548612,0.451388,0.451388,0.548612,1.981272,0.017137,9603.640948,-499.574062,828.877341,9.351308

====================================================================================================
Config 24/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=50.0, tau=0.7, lamda_b=10.0
Epoch [1/40] | train_loss=33087.164162 | val_total=21769.007154 | val_recon=3976.546651 | usage=[0.2536 0.7464] | eff=1.609 | switch=0.0116
Epoch [10/40] | train_loss=15711.190103 | val_total=13297.530405 | val_recon=3370.638563 | usage=[0.4431 0.5569] | eff=1.974 | switch=0.0140
Epoch [20/40] | train_loss=15548.767566 | val_total=13342.186606 | val_recon=3311.253577 | usage=[0.5192 0.4808] | eff=1.997 | switch=0.0207
Epoch [30/40] | train_loss=15472.066643 | val_total=13269.314388 | val_recon=3391.959261 | usage=[0.4808 0.5192] | eff=1.997 | switch=0.0141
Epoch [40/40] | train_loss=15410.023089 | val_total=13249.211844 | val_recon=3324.320350 | usage=[0.5019 0.4981] | eff=2.000 | switch=0.0155

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
23,10.0,10.0,50.0,0.7,10.0,39,15.301800,13201.699126,3272.630068,960.109859,...,0.503282,0.496718,0.496718,0.503282,1.999914,0.015711,9601.098594,-115.083908,441.720120,1.334373
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
22,10.0,10.0,50.0,0.5,10.0,23,14.424851,13261.227941,3404.360791,960.351413,...,0.522383,0.477617,0.477617,0.522383,1.996000,0.013330,9603.514135,-66.758273,315.849244,4.262317
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936

====================================================================================================
Config 25/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=75.0, tau=0.5, lamda_b=1.0
Epoch [1/40] | train_loss=36946.692095 | val_total=21444.769475 | val_recon=3768.478090 | usage=[0.8305 0.1695] | eff=1.392 | switch=0.0126
Epoch [10/40] | train_loss=15799.157687 | val_total=13458.065978 | val_recon=3499.464676 | usage=[0.8646 0.1354] | eff=1.306 | switch=0.0044
Epoch [20/40] | train_loss=15670.811527 | val_total=13514.783386 | val_recon=3585.423092 | usage=[0.9058 0.0942] | eff=1.206 | switch=0.0027
Epoch [30/40] | train_loss=15542.832217 | val_total=13349.021463 | val_recon=3415.187798 | usage=[0.8196 0.1804] | eff=1.420 | switch=0.0072
Epoch [40/40] | train_loss=15496.436074 | val_total=13362.892488 | val_recon=3454.312351 | usage=[0.8517 0.1483] | eff=1.338 | switch=0.0055

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
23,10.0,10.0,50.0,0.7,10.0,39,15.301800,13201.699126,3272.630068,960.109859,...,0.503282,0.496718,0.496718,0.503282,1.999914,0.015711,9601.098594,-115.083908,441.720120,1.334373
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
22,10.0,10.0,50.0,0.5,10.0,23,14.424851,13261.227941,3404.360791,960.351413,...,0.522383,0.477617,0.477617,0.522383,1.996000,0.013330,9603.514135,-66.758273,315.849244,4.262317
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936

====================================================================================================
Config 26/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=75.0, tau=0.7, lamda_b=1.0
Epoch [1/40] | train_loss=36703.932407 | val_total=23959.538553 | val_recon=3991.387520 | usage=[0.7191 0.2809] | eff=1.678 | switch=0.0184
Epoch [10/40] | train_loss=15792.785087 | val_total=13472.707870 | val_recon=3525.848619 | usage=[0.8657 0.1343] | eff=1.303 | switch=0.0040
Epoch [20/40] | train_loss=15632.927110 | val_total=13467.994436 | val_recon=3434.047943 | usage=[0.8774 0.1226] | eff=1.274 | switch=0.0078
Early stopping at epoch 28. Best val loss = 13332.524046

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
23,10.0,10.0,50.0,0.7,10.0,39,15.301800,13201.699126,3272.630068,960.109859,...,0.503282,0.496718,0.496718,0.503282,1.999914,0.015711,9601.098594,-115.083908,441.720120,1.334373
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
22,10.0,10.0,50.0,0.5,10.0,23,14.424851,13261.227941,3404.360791,960.351413,...,0.522383,0.477617,0.477617,0.522383,1.996000,0.013330,9603.514135,-66.758273,315.849244,4.262317
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936

====================================================================================================
Config 27/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=75.0, tau=0.5, lamda_b=5.0
Epoch [1/40] | train_loss=36505.624276 | val_total=23598.800874 | val_recon=3840.603885 | usage=[0.7421 0.2579] | eff=1.620 | switch=0.0172
Epoch [10/40] | train_loss=15864.819268 | val_total=13495.378975 | val_recon=3621.506210 | usage=[0.6005 0.3995] | eff=1.922 | switch=0.0066
Epoch [20/40] | train_loss=15784.908457 | val_total=13521.173291 | val_recon=3425.833168 | usage=[0.4954 0.5046] | eff=2.000 | switch=0.0158
Epoch [30/40] | train_loss=15630.359969 | val_total=13418.375397 | val_recon=3492.716415 | usage=[0.5749 0.4251] | eff=1.956 | switch=0.0104
Epoch [40/40] | train_loss=15633.685485 | val_total=13469.191574 | val_recon=3543.274295 | usage=[0.3982 0.6018] | eff=1.920 | switch=0.0098

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
23,10.0,10.0,50.0,0.7,10.0,39,15.301800,13201.699126,3272.630068,960.109859,...,0.503282,0.496718,0.496718,0.503282,1.999914,0.015711,9601.098594,-115.083908,441.720120,1.334373
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
22,10.0,10.0,50.0,0.5,10.0,23,14.424851,13261.227941,3404.360791,960.351413,...,0.522383,0.477617,0.477617,0.522383,1.996000,0.013330,9603.514135,-66.758273,315.849244,4.262317
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936

====================================================================================================
Config 28/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=75.0, tau=0.7, lamda_b=5.0
Epoch [1/40] | train_loss=37840.455043 | val_total=24943.779014 | val_recon=3964.244386 | usage=[0.7855 0.2145] | eff=1.508 | switch=0.0001
Epoch [10/40] | train_loss=15940.898316 | val_total=13575.777027 | val_recon=3516.973967 | usage=[0.6047 0.3953] | eff=1.916 | switch=0.0113
Epoch [20/40] | train_loss=15735.241217 | val_total=13428.195946 | val_recon=3507.622466 | usage=[0.5941 0.4059] | eff=1.932 | switch=0.0092
Epoch [30/40] | train_loss=15687.046767 | val_total=13456.422496 | val_recon=3593.134738 | usage=[0.5754 0.4246] | eff=1.956 | switch=0.0080
Epoch [40/40] | train_loss=15627.741262 | val_total=13414.773847 | val_recon=3489.361834 | usage=[0.6226 0.3774] | eff=1.887 | switch=0.0091

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
23,10.0,10.0,50.0,0.7,10.0,39,15.301800,13201.699126,3272.630068,960.109859,...,0.503282,0.496718,0.496718,0.503282,1.999914,0.015711,9601.098594,-115.083908,441.720120,1.334373
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
22,10.0,10.0,50.0,0.5,10.0,23,14.424851,13261.227941,3404.360791,960.351413,...,0.522383,0.477617,0.477617,0.522383,1.996000,0.013330,9603.514135,-66.758273,315.849244,4.262317
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936

====================================================================================================
Config 29/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=75.0, tau=0.5, lamda_b=10.0
Epoch [1/40] | train_loss=38685.338374 | val_total=22821.380366 | val_recon=3911.759141 | usage=[0.1562 0.8438] | eff=1.358 | switch=0.0076
Epoch [10/40] | train_loss=16104.808312 | val_total=14698.413553 | val_recon=3672.853984 | usage=[0.1648 0.8352] | eff=1.380 | switch=0.0021
Epoch [20/40] | train_loss=15726.732887 | val_total=13551.947933 | val_recon=3468.049732 | usage=[0.3456 0.6544] | eff=1.826 | switch=0.0081
Epoch [30/40] | train_loss=15653.117122 | val_total=13449.715223 | val_recon=3390.808078 | usage=[0.3801 0.6199] | eff=1.891 | switch=0.0109
Epoch [40/40] | train_loss=15665.461970 | val_total=13943.888911 | val_recon=3527.035821 | usage=[0.2442 0.7558] | eff=1.585 | switch=0.0049

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
23,10.0,10.0,50.0,0.7,10.0,39,15.301800,13201.699126,3272.630068,960.109859,...,0.503282,0.496718,0.496718,0.503282,1.999914,0.015711,9601.098594,-115.083908,441.720120,1.334373
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
22,10.0,10.0,50.0,0.5,10.0,23,14.424851,13261.227941,3404.360791,960.351413,...,0.522383,0.477617,0.477617,0.522383,1.996000,0.013330,9603.514135,-66.758273,315.849244,4.262317
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936

====================================================================================================
Config 30/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=75.0, tau=0.7, lamda_b=10.0
Epoch [1/40] | train_loss=37027.514623 | val_total=23379.815580 | val_recon=4020.311059 | usage=[0.1618 0.8382] | eff=1.372 | switch=0.0027
Epoch [10/40] | train_loss=16005.681999 | val_total=13629.312997 | val_recon=3507.878229 | usage=[0.4269 0.5731] | eff=1.958 | switch=0.0120
Epoch [20/40] | train_loss=15801.371469 | val_total=13563.928259 | val_recon=3451.065978 | usage=[0.3895 0.6105] | eff=1.907 | switch=0.0120
Epoch [30/40] | train_loss=15729.659000 | val_total=13445.037560 | val_recon=3606.645370 | usage=[0.4439 0.5561] | eff=1.975 | switch=0.0071
Epoch [40/40] | train_loss=15622.106755 | val_total=13453.931240 | val_recon=3487.967160 | usage=[0.3976 0.6024] | eff=1.920 | switch=0.0095

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
23,10.0,10.0,50.0,0.7,10.0,39,15.301800,13201.699126,3272.630068,960.109859,...,0.503282,0.496718,0.496718,0.503282,1.999914,0.015711,9601.098594,-115.083908,441.720120,1.334373
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
22,10.0,10.0,50.0,0.5,10.0,23,14.424851,13261.227941,3404.360791,960.351413,...,0.522383,0.477617,0.477617,0.522383,1.996000,0.013330,9603.514135,-66.758273,315.849244,4.262317
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936

====================================================================================================
Config 31/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=100.0, tau=0.5, lamda_b=1.0
Epoch [1/40] | train_loss=37825.565239 | val_total=23199.173688 | val_recon=3686.122417 | usage=[0.2238 0.7762] | eff=1.532 | switch=0.0198
Epoch [10/40] | train_loss=15839.361554 | val_total=13529.868839 | val_recon=3501.212888 | usage=[0.1568 0.8432] | eff=1.360 | switch=0.0047
Epoch [20/40] | train_loss=15682.598741 | val_total=13445.876192 | val_recon=3521.547794 | usage=[0.1481 0.8519] | eff=1.338 | switch=0.0036
Epoch [30/40] | train_loss=15604.336155 | val_total=13455.968203 | val_recon=3527.964080 | usage=[0.1375 0.8625] | eff=1.311 | switch=0.0039
Epoch [40/40] | train_loss=15574.007561 | val_total=13466.342210 | val_recon=3545.468700 | usage=[0.1201 0.8799] | eff=1.268 | switch=0.0032

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
23,10.0,10.0,50.0,0.7,10.0,39,15.301800,13201.699126,3272.630068,960.109859,...,0.503282,0.496718,0.496718,0.503282,1.999914,0.015711,9601.098594,-115.083908,441.720120,1.334373
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
22,10.0,10.0,50.0,0.5,10.0,23,14.424851,13261.227941,3404.360791,960.351413,...,0.522383,0.477617,0.477617,0.522383,1.996000,0.013330,9603.514135,-66.758273,315.849244,4.262317
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936

====================================================================================================
Config 32/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=100.0, tau=0.7, lamda_b=1.0
Epoch [1/40] | train_loss=44881.565465 | val_total=29857.605723 | val_recon=3869.935364 | usage=[0.6762 0.3238] | eff=1.779 | switch=0.0143
Epoch [10/40] | train_loss=16049.694359 | val_total=13713.212639 | val_recon=3630.089229 | usage=[0.8394 0.1606] | eff=1.369 | switch=0.0058
Epoch [20/40] | train_loss=15820.611056 | val_total=13563.975159 | val_recon=3639.599960 | usage=[0.8314 0.1686] | eff=1.389 | switch=0.0045
Epoch [30/40] | train_loss=15765.922899 | val_total=13521.154014 | val_recon=3664.155803 | usage=[0.7294 0.2706] | eff=1.652 | switch=0.0050
Epoch [40/40] | train_loss=15881.458982 | val_total=13588.588037 | val_recon=3464.768482 | usage=[0.5255 0.4745] | eff=1.995 | switch=0.0123

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
23,10.0,10.0,50.0,0.7,10.0,39,15.301800,13201.699126,3272.630068,960.109859,...,0.503282,0.496718,0.496718,0.503282,1.999914,0.015711,9601.098594,-115.083908,441.720120,1.334373
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
22,10.0,10.0,50.0,0.5,10.0,23,14.424851,13261.227941,3404.360791,960.351413,...,0.522383,0.477617,0.477617,0.522383,1.996000,0.013330,9603.514135,-66.758273,315.849244,4.262317
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936

====================================================================================================
Config 33/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=100.0, tau=0.5, lamda_b=5.0
Epoch [1/40] | train_loss=40321.296813 | val_total=24113.847774 | val_recon=4034.732065 | usage=[0.1525 0.8475] | eff=1.349 | switch=0.0047
Epoch [10/40] | train_loss=16145.623144 | val_total=14262.470191 | val_recon=3751.845042 | usage=[0.1789 0.8211] | eff=1.416 | switch=0.0009
Epoch [20/40] | train_loss=16002.108204 | val_total=15106.174483 | val_recon=3758.753378 | usage=[0.0699 0.9301] | eff=1.150 | switch=0.0003
Epoch [30/40] | train_loss=15859.320355 | val_total=14174.783784 | val_recon=3698.200417 | usage=[0.1652 0.8348] | eff=1.381 | switch=0.0012
Early stopping at epoch 33. Best val loss = 13810.607114

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
23,10.0,10.0,50.0,0.7,10.0,39,15.301800,13201.699126,3272.630068,960.109859,...,0.503282,0.496718,0.496718,0.503282,1.999914,0.015711,9601.098594,-115.083908,441.720120,1.334373
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
22,10.0,10.0,50.0,0.5,10.0,23,14.424851,13261.227941,3404.360791,960.351413,...,0.522383,0.477617,0.477617,0.522383,1.996000,0.013330,9603.514135,-66.758273,315.849244,4.262317
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936

====================================================================================================
Config 34/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=100.0, tau=0.7, lamda_b=5.0
Epoch [1/40] | train_loss=40360.306320 | val_total=27349.726948 | val_recon=3967.476749 | usage=[0.784 0.216] | eff=1.512 | switch=0.0054
Epoch [10/40] | train_loss=16031.254935 | val_total=13783.219197 | val_recon=3672.771761 | usage=[0.7286 0.2714] | eff=1.654 | switch=0.0045
Epoch [20/40] | train_loss=15959.666742 | val_total=13681.149444 | val_recon=3557.325616 | usage=[0.653 0.347] | eff=1.829 | switch=0.0085
Epoch [30/40] | train_loss=15844.803287 | val_total=13528.251192 | val_recon=3551.549533 | usage=[0.5536 0.4464] | eff=1.977 | switch=0.0086
Epoch [40/40] | train_loss=15770.193453 | val_total=13570.947734 | val_recon=3672.072933 | usage=[0.6279 0.3721] | eff=1.877 | switch=0.0055

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
23,10.0,10.0,50.0,0.7,10.0,39,15.301800,13201.699126,3272.630068,960.109859,...,0.503282,0.496718,0.496718,0.503282,1.999914,0.015711,9601.098594,-115.083908,441.720120,1.334373
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
22,10.0,10.0,50.0,0.5,10.0,23,14.424851,13261.227941,3404.360791,960.351413,...,0.522383,0.477617,0.477617,0.522383,1.996000,0.013330,9603.514135,-66.758273,315.849244,4.262317
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936

====================================================================================================
Config 35/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=100.0, tau=0.5, lamda_b=10.0
Epoch [1/40] | train_loss=40450.602590 | val_total=28317.292528 | val_recon=3954.271612 | usage=[0.6807 0.3193] | eff=1.769 | switch=0.0292
Epoch [10/40] | train_loss=16060.117711 | val_total=13613.220588 | val_recon=3534.876689 | usage=[0.5854 0.4146] | eff=1.943 | switch=0.0072
Epoch [20/40] | train_loss=15833.153477 | val_total=13549.219595 | val_recon=3470.185215 | usage=[0.6037 0.3963] | eff=1.918 | switch=0.0090
Epoch [30/40] | train_loss=15858.573026 | val_total=13604.170509 | val_recon=3409.324275 | usage=[0.5684 0.4316] | eff=1.963 | switch=0.0131
Early stopping at epoch 34. Best val loss = 13534.087639

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
23,10.0,10.0,50.0,0.7,10.0,39,15.301800,13201.699126,3272.630068,960.109859,...,0.503282,0.496718,0.496718,0.503282,1.999914,0.015711,9601.098594,-115.083908,441.720120,1.334373
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
22,10.0,10.0,50.0,0.5,10.0,23,14.424851,13261.227941,3404.360791,960.351413,...,0.522383,0.477617,0.477617,0.522383,1.996000,0.013330,9603.514135,-66.758273,315.849244,4.262317
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841
2,10.0,10.0,10.0,0.5,5.0,28,15.694473,11988.917727,2947.747118,960.441624,...,0.530912,0.469088,0.469088,0.530912,1.992384,0.058137,9604.416236,-1799.129167,1231.572793,4.310936

====================================================================================================
Config 36/36
Running Mixture-VAE | lamda_m=10.0, lamda_i=10.0, lamda_t=100.0, tau=0.7, lamda_b=10.0
Epoch [1/40] | train_loss=40650.084028 | val_total=29181.780207 | val_recon=3780.867299 | usage=[0.5808 0.4192] | eff=1.949 | switch=0.0271
Epoch [10/40] | train_loss=16224.081175 | val_total=13761.129769 | val_recon=3530.950666 | usage=[0.5958 0.4042] | eff=1.929 | switch=0.0108
Epoch [20/40] | train_loss=15887.856030 | val_total=13578.553458 | val_recon=3579.267886 | usage=[0.5689 0.4311] | eff=1.963 | switch=0.0080
Epoch [30/40] | train_loss=15854.601820 | val_total=13601.498808 | val_recon=3803.268333 | usage=[0.5093 0.4907] | eff=1.999 | switch=0.0045
Epoch [40/40] | train_loss=15803.981891 | val_total=13559.074722 | val_recon=3654.403219 | usage=[0.5586 0.4414] | eff=1.973 | switch=0.0067

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,elapsed_sec,val_total_loss,val_recon_loss,val_mixture_loss,...,usage_0,usage_1,min_usage,max_usage,eff_regimes,switch_rate,weighted_mixture,weighted_info,weighted_transition,weighted_balance
23,10.0,10.0,50.0,0.7,10.0,39,15.301800,13201.699126,3272.630068,960.109859,...,0.503282,0.496718,0.496718,0.503282,1.999914,0.015711,9601.098594,-115.083908,441.720120,1.334373
4,10.0,10.0,10.0,0.5,10.0,37,15.504573,11979.501987,2954.895866,960.234648,...,0.511318,0.488682,0.488682,0.511318,1.998976,0.063931,9602.346483,-1849.020488,1269.642398,1.637267
35,10.0,10.0,100.0,0.7,10.0,35,15.256152,13528.154610,3666.817717,960.138352,...,0.488090,0.511910,0.488090,0.511910,1.998866,0.006261,9601.383520,-28.355838,286.920840,1.388283
16,10.0,10.0,30.0,0.5,10.0,40,15.416002,12966.439587,3055.410374,960.290454,...,0.486738,0.513262,0.486738,0.513262,1.998594,0.020391,9602.904536,-391.274554,696.427637,2.971411
5,10.0,10.0,10.0,0.7,10.0,38,15.407031,11875.041534,2854.414994,960.143469,...,0.514443,0.485557,0.485557,0.514443,1.998333,0.061445,9601.434693,-1846.270432,1263.148583,2.313330
1,10.0,10.0,10.0,0.7,1.0,30,15.705382,11855.988076,2843.971333,960.289721,...,0.483201,0.516799,0.483201,0.516799,1.997745,0.063355,9602.897208,-1868.207286,1277.040922,0.285781
14,10.0,10.0,30.0,0.5,5.0,32,15.269075,12978.403219,3112.882552,960.446964,...,0.521986,0.478014,0.478014,0.521986,1.996140,0.020684,9604.469644,-319.082982,578.018331,2.115743
22,10.0,10.0,50.0,0.5,10.0,23,14.424851,13261.227941,3404.360791,960.351413,...,0.522383,0.477617,0.477617,0.522383,1.996000,0.013330,9603.514135,-66.758273,315.849244,4.262317
8,10.0,10.0,20.0,0.5,5.0,39,15.251406,12688.069555,2861.028418,960.218601,...,0.475777,0.524223,0.475777,0.524223,1.995317,0.027628,9602.186010,-972.697176,1194.396503,3.155333
3,10.0,10.0,10.0,0.7,5.0,34,15.418516,11887.552464,2868.406151,960.397990,...,0.475369,0.524631,0.475369,0.524631,1.995159,0.055020,9603.979904,-1856.012582,1268.322471,2.856841

In [14]:
dates_val = np.load(DATA_DIR / "dates_val_4.npy", allow_pickle=True)
dates_test = np.load(DATA_DIR / "dates_test_4.npy", allow_pickle=True)
panel_features = pd.read_parquet(DATA_DIR / "panel_features_4.parquet")

In [15]:
results_df = pd.DataFrame(results)



def daily_segment_summary(states_2d, dates):
    rows = []

    for i in range(len(dates)):
        s = states_2d[i]

        switches = int(np.sum(s[1:] != s[:-1]))
        segments = switches + 1

        rows.append({
            "date": pd.to_datetime(dates[i]).date(),
            "switches": switches,
            "segments": segments,
        })

    df = pd.DataFrame(rows)

    summary = {
        "median_segments": df["segments"].median(),
        "mean_segments": df["segments"].mean(),
        "p75_segments": df["segments"].quantile(0.75),
        "p90_segments": df["segments"].quantile(0.90),
        "max_segments": df["segments"].max(),
        "one_state_share": (df["segments"] == 1).mean(),
        "multi_state_share": (df["segments"] > 1).mean(),
    }

    return summary, df


daily_rows = []

for _, row in results_df.iterrows():
    key = (
        float(row["lamda_m"]),
        float(row["lamda_i"]),
        float(row["lamda_t"]),
        float(row["tau"]),
        float(row["lamda_b"]),
    )

    model = candidate_models[key]

    # Use validation set for model selection.
    states_val = model.get_predicted_states(val_loader)

    daily_summary, _ = daily_segment_summary(states_val, dates_val)

    daily_rows.append({
        "lamda_m": key[0],
        "lamda_i": key[1],
        "lamda_t": key[2],
        "tau": key[3],
        "lamda_b": key[4],
        **daily_summary,
    })

daily_df = pd.DataFrame(daily_rows)

selection_with_daily = results_df.merge(
    daily_df,
    on=["lamda_m", "lamda_i", "lamda_t", "tau", "lamda_b"],
    how="left"
)

print("Original Mixture-VAE models:", len(results_df))

admissible_df = selection_with_daily[
    (selection_with_daily["min_usage"] >= 0.25) &
    (selection_with_daily["eff_regimes"] >= 1.70) &
    (selection_with_daily["switch_rate"] >= 0.003) &
    (selection_with_daily["switch_rate"] <= 0.050) &
    (selection_with_daily["median_segments"] >= 1) &
    (selection_with_daily["median_segments"] <= 16) &
    (selection_with_daily["p90_segments"] <= 28)
].copy()

print("Admissible Mixture-VAE models under common 2-state criterion:", len(admissible_df))

#Relaxed critiria


if len(admissible_df) == 0:
    print("No strict admissible Mixture-VAE models. Using relaxed 2-state criteria.")

    admissible_df = selection_with_daily[
        (selection_with_daily["min_usage"] >= 0.15) &
        (selection_with_daily["eff_regimes"] >= 1.50) &
        (selection_with_daily["switch_rate"] >= 0.001) &
        (selection_with_daily["switch_rate"] <= 0.070) &
        (selection_with_daily["median_segments"] <= 22) &
        (selection_with_daily["p90_segments"] <= 34)
    ].copy()

    print("Relaxed admissible Mixture-VAE models:", len(admissible_df))

selection_df = admissible_df.sort_values(
    ["val_recon_loss", "val_total_loss"],
    ascending=[True, True]
).copy()

display_cols = [
    "lamda_m", "lamda_i", "lamda_t", "tau", "lamda_b",
    "best_epoch",
    "val_recon_loss", "val_total_loss",
    "min_usage", "eff_regimes", "switch_rate",
    "median_segments", "mean_segments", "p75_segments",
    "p90_segments", "max_segments", "one_state_share",
]

display(selection_df[display_cols].head(15))

Original Mixture-VAE models: 36
Admissible Mixture-VAE models under common 2-state criterion: 24

,lamda_m,lamda_i,lamda_t,tau,lamda_b,best_epoch,val_recon_loss,val_total_loss,min_usage,eff_regimes,switch_rate,median_segments,mean_segments,p75_segments,p90_segments,max_segments,one_state_share
9,10.0,10.0,20.0,0.7,5.0,38,2752.145394,12578.501789,0.417537,1.947040,0.024237,10.0,10.452305,13.0,15.0,25,0.002385
11,10.0,10.0,20.0,0.7,10.0,38,2758.670906,12581.158983,0.445064,1.976144,0.024502,10.0,10.555644,13.0,15.0,23,0.000795
7,10.0,10.0,20.0,0.7,1.0,35,2809.165143,12612.795509,0.418863,1.948686,0.024296,10.0,10.475358,13.0,15.0,22,0.000795
17,10.0,10.0,30.0,0.7,10.0,35,2850.862530,12848.308227,0.426663,1.957879,0.017087,7.0,7.663752,9.0,11.0,21,0.007949
10,10.0,10.0,20.0,0.5,10.0,33,2854.356816,12705.368243,0.450298,1.980431,0.028474,12.0,12.104928,15.0,17.0,29,0.000795
8,10.0,10.0,20.0,0.5,5.0,39,2861.028418,12688.069555,0.475777,1.995317,0.027628,12.0,11.775040,14.0,17.0,26,0.000000
13,10.0,10.0,30.0,0.7,1.0,35,2894.318313,12824.691375,0.337416,1.808753,0.016402,7.0,7.396661,9.0,11.0,18,0.015898
6,10.0,10.0,20.0,0.5,1.0,31,2901.664199,12706.095390,0.426174,1.957328,0.027005,11.0,11.531797,14.0,16.0,30,0.000795
15,10.0,10.0,30.0,0.7,5.0,36,2916.268879,12858.564587,0.451388,1.981272,0.017137,7.0,7.683625,9.0,11.0,19,0.002385
16,10.0,10.0,30.0,0.5,10.0,40,3055.410374,12966.439587,0.486738,1.998594,0.020391,9.0,8.952305,11.0,13.0,20,0.000000
14,10.0,10.0,30.0,0.5,5.0,32,3112.882552,12978.403219,0.478014,1.996140,0.020684,9.0,9.066773,11.0,13.0,18,0.000795
12,10.0,10.0,30.0,0.5,1.0,39,3192.266594,13031.734499,0.416792,1.946104,0.019253,8.0,8.508744,10.0,12.0,22,0.001590
21,10.0,10.0,50.0,0.7,5.0,36,3263.590670,13272.412758,0.369543,1.872526,0.015933,7.0,7.213831,9.0,11.0,18,0.013514
23,10.0,10.0,50.0,0.7,10.0,39,3272.630068,13201.699126,0.496718,1.999914,0.015711,7.0,7.127186,9.0,10.0,18,0.001590
20,10.0,10.0,50.0,0.5,5.0,28,3335.550527,13254.747615,0.366846,1.867553,0.012768,6.0,5.979332,7.0,9.0,14,0.015898

In [16]:
best_row = selection_df.iloc[0]

final_key = (
    float(best_row["lamda_m"]),
    float(best_row["lamda_i"]),
    float(best_row["lamda_t"]),
    float(best_row["tau"]),
    float(best_row["lamda_b"]),
)

print("Selected final key:", final_key)

final_model = candidate_models[final_key]
final_history = candidate_histories[final_key]

Selected final key: (10.0, 10.0, 20.0, 0.7, 5.0)

In [17]:
final_test_states_2d = final_model.get_predicted_states(test_loader)
final_test_states_flat = final_test_states_2d.reshape(-1)

print("Final test states 2D:", final_test_states_2d.shape)
print("Final test states flat:", final_test_states_flat.shape)

Final test states 2D: (1453, 391)
Final test states flat: (568123,)

we will retrain for the final keys for 2 states cause we got disconnected

In [10]:
from types import SimpleNamespace
import numpy as np
import pandas as pd
import torch
import random

def make_mvae_args(n_cluster, lamda_b):
    return SimpleNamespace(
        name="mixture_vae",
        feature=X_train.shape[-1],
        seq_len=X_train.shape[1],
        n_cluster=n_cluster,

        hidden_dim=16,
        tau=0.7,
        hard=False,

        reconstruction_on_s=True,
        reconstruction_on_z="p",

        lamda_m=10.0,
        lamda_i=10.0,
        lamda_t=20.0,
        lamda_b=lamda_b,

        transition="jump",
        jump_mx=None,

        loss_mode="sum",
        loss_clamp=batch_size * X_train.shape[1] * 10,
        s_clamp=5.0,

        eps=1e-8,
        logvar_min=-10.0,
        logvar_max=10.0,

        s_x_type="lstm",
        s_x_lstm_hidden=64,
        s_x_lstm_layers=1,
        s_x_dropout=0.1,

        z_sx_type="mlp",
        z_sx_hiddens=[128, 128],
        z_sx_dropout=0.1,

        x_sz_type="mlp",
        x_sz_hiddens=[128, 128],
        x_sz_dropout=0.1,

        x_z_type="mlp",
        x_z_hiddens=[128, 128],
        x_z_dropout=0.1,
    )

args_mvae_2 = make_mvae_args(n_cluster=2, lamda_b=5.0)
selected_key_mvae_2 = (10.0, 10.0, 20.0, 0.7, 5.0)
print(args_mvae_2)

namespace(name='mixture_vae', feature=19, seq_len=391, n_cluster=2, hidden_dim=16, tau=0.7, hard=False, reconstruction_on_s=True, reconstruction_on_z='p', lamda_m=10.0, lamda_i=10.0, lamda_t=20.0, lamda_b=5.0, transition='jump', jump_mx=None, loss_mode='sum', loss_clamp=1000960, s_clamp=5.0, eps=1e-08, logvar_min=-10.0, logvar_max=10.0, s_x_type='lstm', s_x_lstm_hidden=64, s_x_lstm_layers=1, s_x_dropout=0.1, z_sx_type='mlp', z_sx_hiddens=[128, 128], z_sx_dropout=0.1, x_sz_type='mlp', x_sz_hiddens=[128, 128], x_sz_dropout=0.1, x_z_type='mlp', x_z_hiddens=[128, 128], x_z_dropout=0.1)

In [11]:
vae_run_2 = VAEModule(args_mvae_2)

history_mvae_2 = vae_run_2.fit(
    train_loader=train_loader,
    val_loader=val_loader,
    lr=1e-3,
    epochs=40,
    weight_decay=1e-5,
    patience=15,
    verbose=True,
)

print("Finished final 2-state Mixture-VAE.")

Epoch [1/40] | train_loss=25628.368707 | val_total=17199.168919 | val_recon=4001.026381 | usage=[0.5539 0.4461] | eff=1.977 | switch=0.0238
Epoch [10/40] | train_loss=14980.661943 | val_total=12833.482909 | val_recon=2975.344098 | usage=[0.5957 0.4043] | eff=1.929 | switch=0.0305
Epoch [20/40] | train_loss=14706.509779 | val_total=12757.815183 | val_recon=2909.870280 | usage=[0.5795 0.4205] | eff=1.951 | switch=0.0256
Epoch [30/40] | train_loss=14617.347315 | val_total=12728.035771 | val_recon=2897.008496 | usage=[0.5682 0.4318] | eff=1.963 | switch=0.0249
Epoch [40/40] | train_loss=14569.658548 | val_total=12695.886924 | val_recon=2876.160622 | usage=[0.5807 0.4193] | eff=1.949 | switch=0.0239
Finished final 2-state Mixture-VAE.

In [12]:
states_train_mvae_2 = vae_run_2.get_predicted_states(train_loader)
states_val_mvae_2   = vae_run_2.get_predicted_states(val_loader)
states_test_mvae_2  = vae_run_2.get_predicted_states(test_loader)

states_train_mvae_2 = np.asarray(states_train_mvae_2).reshape(X_train.shape[0], X_train.shape[1])
states_val_mvae_2   = np.asarray(states_val_mvae_2).reshape(X_val.shape[0], X_val.shape[1])
states_test_mvae_2  = np.asarray(states_test_mvae_2).reshape(X_test.shape[0], X_test.shape[1])

print("train:", states_train_mvae_2.shape)
print("val:", states_val_mvae_2.shape)
print("test:", states_test_mvae_2.shape)

np.save(OUT_DIR / "mvae_2state_train_states.npy", states_train_mvae_2)
np.save(OUT_DIR / "mvae_2state_val_states.npy", states_val_mvae_2)
np.save(OUT_DIR / "mvae_2state_test_states.npy", states_test_mvae_2)

torch.save(
    {
        "selected_key": selected_key_mvae_2,
        "args": vars(args_mvae_2),
        "history": history_mvae_2,
    },
    OUT_DIR / "mvae_2state_selected_config.pt"
)

print("Saved 2-state Mixture-VAE states/config.")

train: (5522, 391)
val: (1258, 391)
test: (1453, 391)
Saved 2-state Mixture-VAE states/config.

In [13]:
states_val_mvae_2 = np.load(OUT_DIR / "mvae_2state_val_states.npy")
states_test_mvae_2 = np.load(OUT_DIR / "mvae_2state_test_states.npy")

print("2-state val:", states_val_mvae_2.shape)
print("2-state test:", states_test_mvae_2.shape)

2-state val: (1258, 391)
2-state test: (1453, 391)

In [14]:
import numpy as np
import pandas as pd

econ_cols = [
    "ret_mean_30", "ret_mean_60", "ret_mean_120",
    "momentum_30", "momentum_60", "momentum_120",
    "trend_strength_30", "trend_strength_60", "trend_strength_120",
    "ret_std_60", "rv_60",
]

future_cols = ["future_ret_30", "future_ret_60", "future_ret_120"]


def add_future_returns(panel, return_col="ret_1", date_col="date", horizons=(30, 60, 120)):
    panel = panel.copy()

    for h in horizons:
        col = f"future_ret_{h}"

        if col in panel.columns:
            continue

        panel[col] = (
            panel
            .groupby(date_col)[return_col]
            .transform(
                lambda s: s.shift(-1)
                           .rolling(window=h, min_periods=1)
                           .sum()
                           .shift(-(h - 1))
            )
        )

    return panel


def transition_matrix_from_states(states, n_states):
    states = np.asarray(states)
    counts = np.zeros((n_states, n_states), dtype=float)

    prev_states = states[:, :-1].reshape(-1)
    next_states = states[:, 1:].reshape(-1)

    for i, j in zip(prev_states, next_states):
        counts[int(i), int(j)] += 1

    row_sums = counts.sum(axis=1, keepdims=True)

    trans = np.divide(
        counts,
        row_sums,
        out=np.zeros_like(counts),
        where=row_sums != 0,
    )

    return trans


def regime_diagnostics_from_states(states, n_states):
    states = np.asarray(states)
    flat = states.reshape(-1)

    usage = np.array([(flat == k).mean() for k in range(n_states)])

    effective_regimes = np.exp(
        -np.sum(usage * np.log(usage + 1e-12))
    )

    switch_rate = np.mean(states[:, 1:] != states[:, :-1])

    trans = transition_matrix_from_states(states, n_states)

    return {
        "usage": usage,
        "effective_regimes": float(effective_regimes),
        "switch_rate": float(switch_rate),
        "transition_matrix": trans,
        "transition_diag": np.diag(trans),
        "avg_transition_diag": float(np.diag(trans).mean()),
    }


def daily_segment_summary_from_states(states, dates):
    states = np.asarray(states)

    rows = []

    for i in range(states.shape[0]):
        s = states[i]
        switches = int(np.sum(s[1:] != s[:-1]))
        segments = switches + 1

        rows.append({
            "date": pd.to_datetime(dates[i]).date(),
            "switches": switches,
            "segments": segments,
        })

    df = pd.DataFrame(rows)

    summary = {
        "median_segments": float(df["segments"].median()),
        "mean_segments": float(df["segments"].mean()),
        "p75_segments": float(df["segments"].quantile(0.75)),
        "p90_segments": float(df["segments"].quantile(0.90)),
        "max_segments": int(df["segments"].max()),
        "one_state_share": float((df["segments"] == 1).mean()),
        "multi_state_share": float((df["segments"] > 1).mean()),
    }

    return summary, df


def regime_aware_return_diagnostic(
    val_panel,
    test_panel,
    state_col,
    return_col="ret_1",
    date_col="date",
):
    # Choose investable state using validation set only
    val_state_mean_ret = (
        val_panel
        .groupby(state_col)[return_col]
        .mean()
        .sort_index()
    )

    invest_state = int(val_state_mean_ret.idxmax())

    test_tmp = test_panel.copy()
    test_tmp["invest"] = (test_tmp[state_col] == invest_state).astype(float)
    test_tmp["strategy_ret"] = test_tmp["invest"] * test_tmp[return_col]

    daily_strategy_ret = (
        test_tmp
        .groupby(date_col)["strategy_ret"]
        .sum()
    )

    daily_buy_hold_ret = (
        test_tmp
        .groupby(date_col)[return_col]
        .sum()
    )

    regime_std = daily_strategy_ret.std()
    bh_std = daily_buy_hold_ret.std()

    return {
        "invest_state": invest_state,
        "validation_state_mean_returns": val_state_mean_ret,
        "avg_daily_regime_return": float(daily_strategy_ret.mean()),
        "std_daily_regime_return": float(regime_std),
        "avg_daily_buy_hold_return": float(daily_buy_hold_ret.mean()),
        "std_daily_buy_hold_return": float(bh_std),
        "diagnostic_sharpe_regime": float(daily_strategy_ret.mean() / regime_std) if regime_std != 0 else np.nan,
        "diagnostic_sharpe_buy_hold": float(daily_buy_hold_ret.mean() / bh_std) if bh_std != 0 else np.nan,
        "annualized_diagnostic_sharpe_regime": float(np.sqrt(252) * daily_strategy_ret.mean() / regime_std) if regime_std != 0 else np.nan,
        "annualized_diagnostic_sharpe_buy_hold": float(np.sqrt(252) * daily_buy_hold_ret.mean() / bh_std) if bh_std != 0 else np.nan,
        "daily_strategy_returns": daily_strategy_ret,
        "daily_buy_hold_returns": daily_buy_hold_ret,
    }


def compute_model_thesis_outputs(
    states_val,
    states_test,
    val_panel,
    test_panel,
    n_states,
    state_col,
    model_name,
    selected_key=None,
    dates_test=None,
):
    states_val = np.asarray(states_val)
    states_test = np.asarray(states_test)

    val_tmp = val_panel.copy()
    test_tmp = test_panel.copy()

    # Safety checks
    assert len(val_tmp) == states_val.size, (
        f"val_panel rows {len(val_tmp)} do not match states_val size {states_val.size}"
    )
    assert len(test_tmp) == states_test.size, (
        f"test_panel rows {len(test_tmp)} do not match states_test size {states_test.size}"
    )

    val_tmp[state_col] = states_val.reshape(-1)
    test_tmp[state_col] = states_test.reshape(-1)

    # Make sure future-return columns exist
    val_tmp = add_future_returns(val_tmp)
    test_tmp = add_future_returns(test_tmp)

    econ_summary = (
        test_tmp
        .groupby(state_col)[econ_cols]
        .mean()
    )

    future_summary = (
        test_tmp
        .groupby(state_col)[future_cols]
        .agg(["mean", "std", "count"])
    )

    diag = regime_diagnostics_from_states(states_test, n_states=n_states)

    if dates_test is None:
        unique_dates = (
            test_tmp[["date"]]
            .drop_duplicates()
            .sort_values("date")["date"]
            .values
        )
        dates_for_segments = unique_dates
    else:
        dates_for_segments = dates_test

    daily_summary, daily_segments = daily_segment_summary_from_states(
        states_test,
        dates_for_segments
    )

    rar = regime_aware_return_diagnostic(
        val_panel=val_tmp,
        test_panel=test_tmp,
        state_col=state_col,
        return_col="ret_1",
        date_col="date",
    )

    compact = {
        "model": model_name,
        "states": n_states,
        "selected_key": str(selected_key),
        "usage": str(np.round(diag["usage"], 6)),
        "effective_regimes": diag["effective_regimes"],
        "switch_rate": diag["switch_rate"],
        "transition_diag": str(np.round(diag["transition_diag"], 6)),
        "avg_transition_diag": diag["avg_transition_diag"],
        "median_segments": daily_summary["median_segments"],
        "mean_segments": daily_summary["mean_segments"],
        "p75_segments": daily_summary["p75_segments"],
        "p90_segments": daily_summary["p90_segments"],
        "max_segments": daily_summary["max_segments"],
        "one_state_share": daily_summary["one_state_share"],
        "invest_state": rar["invest_state"],
        "avg_daily_regime_return": rar["avg_daily_regime_return"],
        "avg_daily_buy_hold_return": rar["avg_daily_buy_hold_return"],
        "diagnostic_sharpe_regime": rar["diagnostic_sharpe_regime"],
        "diagnostic_sharpe_buy_hold": rar["diagnostic_sharpe_buy_hold"],
        "annualized_diagnostic_sharpe_regime": rar["annualized_diagnostic_sharpe_regime"],
        "annualized_diagnostic_sharpe_buy_hold": rar["annualized_diagnostic_sharpe_buy_hold"],
    }

    compact_df = pd.DataFrame([compact])

    return {
        "val_panel": val_tmp,
        "test_panel": test_tmp,
        "econ_summary": econ_summary,
        "future_summary": future_summary,
        "diagnostics": diag,
        "daily_summary": daily_summary,
        "daily_segments": daily_segments,
        "regime_aware_return": rar,
        "compact_df": compact_df,
    }

print("Helper functions ready.")

Helper functions ready.

In [15]:
import numpy as np
import pandas as pd

# Load panel if needed
if "panel_features" not in globals():
    panel_features = pd.read_parquet(DATA_DIR / "panel_features_4.parquet")

# Load date arrays
dates_train = np.load(DATA_DIR / "dates_train_4.npy", allow_pickle=True)
dates_val   = np.load(DATA_DIR / "dates_val_4.npy", allow_pickle=True)
dates_test  = np.load(DATA_DIR / "dates_test_4.npy", allow_pickle=True)

dates_train = pd.to_datetime(dates_train)
dates_val   = pd.to_datetime(dates_val)
dates_test  = pd.to_datetime(dates_test)

# Prepare panel
panel_features["date"] = pd.to_datetime(panel_features["date"])

panel_features = (
    panel_features
    .sort_values(["date", "m_index"])
    .reset_index(drop=True)
)

# Build validation/test panels
val_panel = (
    panel_features[panel_features["date"].isin(dates_val)]
    .sort_values(["date", "m_index"])
    .reset_index(drop=True)
)

test_panel = (
    panel_features[panel_features["date"].isin(dates_test)]
    .sort_values(["date", "m_index"])
    .reset_index(drop=True)
)

print("val_panel:", val_panel.shape)
print("test_panel:", test_panel.shape)

print("Expected val rows:", states_val_mvae_2.size)
print("Expected test rows:", states_test_mvae_2.size)

assert len(val_panel) == states_val_mvae_2.size
assert len(test_panel) == states_test_mvae_2.size

print("val_panel and test_panel are ready.")

val_panel: (491878, 34)
test_panel: (568123, 34)
Expected val rows: 491878
Expected test rows: 568123
val_panel and test_panel are ready.

In [16]:
selected_key_mvae_2 = (10.0, 10.0, 20.0, 0.7, 5.0)

out_mvae_2 = compute_model_thesis_outputs(
    states_val=states_val_mvae_2,
    states_test=states_test_mvae_2,
    val_panel=val_panel,
    test_panel=test_panel,
    n_states=2,
    state_col="state_mvae_2",
    model_name="Mixture-VAE 2-state",
    selected_key=selected_key_mvae_2,
    dates_test=dates_test,
)

display(out_mvae_2["compact_df"])
display(out_mvae_2["econ_summary"])
display(out_mvae_2["future_summary"])

print("2-state transition matrix:")
print(np.round(out_mvae_2["diagnostics"]["transition_matrix"], 6))

print("\n2-state validation mean returns:")
print(out_mvae_2["regime_aware_return"]["validation_state_mean_returns"])

,model,states,selected_key,usage,effective_regimes,switch_rate,transition_diag,avg_transition_diag,median_segments,mean_segments,...,p90_segments,max_segments,one_state_share,invest_state,avg_daily_regime_return,avg_daily_buy_hold_return,diagnostic_sharpe_regime,diagnostic_sharpe_buy_hold,annualized_diagnostic_sharpe_regime,annualized_diagnostic_sharpe_buy_hold
0,Mixture-VAE 2-state,2,"(10.0, 10.0, 20.0, 0.7, 5.0)",[0.581216 0.418784],1.973674,0.025103,[0.977333 0.971515],0.974424,11.0,10.790089,...,16.0,26,0.002065,0,0.004066,0.000497,0.384524,0.0373,6.104126,0.592127

,ret_mean_30,ret_mean_60,ret_mean_120,momentum_30,momentum_60,momentum_120,trend_strength_30,trend_strength_60,trend_strength_120,ret_std_60,rv_60
state_mvae_2,,,,,,,,,,,
0,0.000037,0.000025,0.000013,0.001111,0.001484,0.001538,0.60837,0.584057,0.446895,0.000269,0.000009
1,-0.000050,-0.000033,-0.000017,-0.001501,-0.001988,-0.002025,-0.68336,-0.633059,-0.441414,0.000360,0.000014

             future_ret_30                   future_ret_60                    \
                      mean       std   count          mean       std   count
state_mvae_2
0                 0.000046  0.002451  308043      0.000083  0.003360  283504
1                -0.000021  0.002704  217943     -0.000032  0.003744  198892

             future_ret_120
                       mean       std   count
state_mvae_2
0                  0.000102  0.004669  234607
1                  0.000014  0.005080  160609

2-state transition matrix:
[[0.977333 0.022667]
 [0.028485 0.971515]]

2-state validation mean returns:
state_mvae_2
0    0.000010
1   -0.000013
Name: ret_1, dtype: float64

In [59]:
# SAVE MIXTURE-VAE RESULTS

out_mvae_2["compact_df"].to_csv(
    OUT_DIR / "summary_mvae_2state_metrics.csv",
    index=False
)

out_mvae_2["econ_summary"].to_csv(
    OUT_DIR / "econ_summary_mvae_2.csv"
)

out_mvae_2["future_summary"].to_csv(
    OUT_DIR / "future_summary_mvae_2.csv"
)

out_mvae_2["daily_segments"].to_csv(
    OUT_DIR / "mvae_2state_test_daily_segments.csv",
    index=False
)

out_mvae_2["regime_aware_return"]["daily_strategy_returns"].to_csv(
    OUT_DIR / "mvae_2state_daily_regime_aware_returns.csv"
)

out_mvae_2["regime_aware_return"]["daily_buy_hold_returns"].to_csv(
    OUT_DIR / "mvae_2state_daily_buy_hold_returns.csv"
)

out_mvae_2["test_panel"].to_parquet(
    OUT_DIR / "test_panel_mvae_2state.parquet",
    index=False
)

print("Saved Mixture-VAE individual outputs.")

Saved Mixture-VAE individual outputs.